### ISSUE TITLE
Use `.codecov.yml` file for codecov, makes it checked in.

### ISSUE THREAD

**Issue by andmos** [andmos/BikeshareClient#66]
Example:
```yml
coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%

ignore:
  - test      # - tests
```
